//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Core.Objects;
using System.Linq;

public partial class AktiviteEntities : DbContext
{
    public AktiviteEntities()
        : base("name=AktiviteEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual ObjectResult<S_Cagri_Result> S_Cagri(Nullable<int> iD, Nullable<int> danismanID, Nullable<int> cagriDurumu)
    {
        var iDParameter = iD.HasValue ?
            new ObjectParameter("ID", iD) :
            new ObjectParameter("ID", typeof(int));

        var danismanIDParameter = danismanID.HasValue ?
            new ObjectParameter("DanismanID", danismanID) :
            new ObjectParameter("DanismanID", typeof(int));

        var cagriDurumuParameter = cagriDurumu.HasValue ?
            new ObjectParameter("CagriDurumu", cagriDurumu) :
            new ObjectParameter("CagriDurumu", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Cagri_Result>("S_Cagri", iDParameter, danismanIDParameter, cagriDurumuParameter);
    }

    public virtual ObjectResult<S_CagriChart1_Result> S_CagriChart1(Nullable<int> iD, Nullable<System.DateTime> mINDATE, Nullable<System.DateTime> mAXDATE, Nullable<System.Guid> userId)
    {
        var iDParameter = iD.HasValue ?
            new ObjectParameter("ID", iD) :
            new ObjectParameter("ID", typeof(int));

        var mINDATEParameter = mINDATE.HasValue ?
            new ObjectParameter("MINDATE", mINDATE) :
            new ObjectParameter("MINDATE", typeof(System.DateTime));

        var mAXDATEParameter = mAXDATE.HasValue ?
            new ObjectParameter("MAXDATE", mAXDATE) :
            new ObjectParameter("MAXDATE", typeof(System.DateTime));

        var userIdParameter = userId.HasValue ?
            new ObjectParameter("UserId", userId) :
            new ObjectParameter("UserId", typeof(System.Guid));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_CagriChart1_Result>("S_CagriChart1", iDParameter, mINDATEParameter, mAXDATEParameter, userIdParameter);
    }

    public virtual ObjectResult<S_CagriChart2_Result> S_CagriChart2(Nullable<System.DateTime> mINDATE, Nullable<System.DateTime> mAXDATE, Nullable<System.Guid> userId)
    {
        var mINDATEParameter = mINDATE.HasValue ?
            new ObjectParameter("MINDATE", mINDATE) :
            new ObjectParameter("MINDATE", typeof(System.DateTime));

        var mAXDATEParameter = mAXDATE.HasValue ?
            new ObjectParameter("MAXDATE", mAXDATE) :
            new ObjectParameter("MAXDATE", typeof(System.DateTime));

        var userIdParameter = userId.HasValue ?
            new ObjectParameter("UserId", userId) :
            new ObjectParameter("UserId", typeof(System.Guid));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_CagriChart2_Result>("S_CagriChart2", mINDATEParameter, mAXDATEParameter, userIdParameter);
    }

    public virtual ObjectResult<I_Destec_Istek_Result> I_Destec_Istek(string extTicNo, string altTicNo, string ilgKisi, Nullable<System.DateTime> istekTar, string sirAdi, string aciklama, Nullable<System.Guid> userId, Nullable<int> onemDerecesi, string moduller, string sirketKodu, string kisiMail, Nullable<System.Guid> sirketId)
    {
        var extTicNoParameter = extTicNo != null ?
            new ObjectParameter("ExtTicNo", extTicNo) :
            new ObjectParameter("ExtTicNo", typeof(string));

        var altTicNoParameter = altTicNo != null ?
            new ObjectParameter("AltTicNo", altTicNo) :
            new ObjectParameter("AltTicNo", typeof(string));

        var ilgKisiParameter = ilgKisi != null ?
            new ObjectParameter("IlgKisi", ilgKisi) :
            new ObjectParameter("IlgKisi", typeof(string));

        var istekTarParameter = istekTar.HasValue ?
            new ObjectParameter("IstekTar", istekTar) :
            new ObjectParameter("IstekTar", typeof(System.DateTime));

        var sirAdiParameter = sirAdi != null ?
            new ObjectParameter("SirAdi", sirAdi) :
            new ObjectParameter("SirAdi", typeof(string));

        var aciklamaParameter = aciklama != null ?
            new ObjectParameter("Aciklama", aciklama) :
            new ObjectParameter("Aciklama", typeof(string));

        var userIdParameter = userId.HasValue ?
            new ObjectParameter("UserId", userId) :
            new ObjectParameter("UserId", typeof(System.Guid));

        var onemDerecesiParameter = onemDerecesi.HasValue ?
            new ObjectParameter("OnemDerecesi", onemDerecesi) :
            new ObjectParameter("OnemDerecesi", typeof(int));

        var modullerParameter = moduller != null ?
            new ObjectParameter("Moduller", moduller) :
            new ObjectParameter("Moduller", typeof(string));

        var sirketKoduParameter = sirketKodu != null ?
            new ObjectParameter("SirketKodu", sirketKodu) :
            new ObjectParameter("SirketKodu", typeof(string));

        var kisiMailParameter = kisiMail != null ?
            new ObjectParameter("KisiMail", kisiMail) :
            new ObjectParameter("KisiMail", typeof(string));

        var sirketIdParameter = sirketId.HasValue ?
            new ObjectParameter("SirketId", sirketId) :
            new ObjectParameter("SirketId", typeof(System.Guid));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<I_Destec_Istek_Result>("I_Destec_Istek", extTicNoParameter, altTicNoParameter, ilgKisiParameter, istekTarParameter, sirAdiParameter, aciklamaParameter, userIdParameter, onemDerecesiParameter, modullerParameter, sirketKoduParameter, kisiMailParameter, sirketIdParameter);
    }

    public virtual ObjectResult<S_Modul_Result> S_Modul(Nullable<int> iD)
    {
        var iDParameter = iD.HasValue ?
            new ObjectParameter("ID", iD) :
            new ObjectParameter("ID", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Modul_Result>("S_Modul", iDParameter);
    }

    public virtual ObjectResult<S_Tip_Result> S_Tip(Nullable<int> ayirac)
    {
        var ayiracParameter = ayirac.HasValue ?
            new ObjectParameter("Ayirac", ayirac) :
            new ObjectParameter("Ayirac", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Tip_Result>("S_Tip", ayiracParameter);
    }

    public virtual ObjectResult<S_DestecChartCagriDurum_Result> S_DestecChartCagriDurum(Nullable<System.DateTime> mINDATE, Nullable<System.DateTime> mAXDATE)
    {
        var mINDATEParameter = mINDATE.HasValue ?
            new ObjectParameter("MINDATE", mINDATE) :
            new ObjectParameter("MINDATE", typeof(System.DateTime));

        var mAXDATEParameter = mAXDATE.HasValue ?
            new ObjectParameter("MAXDATE", mAXDATE) :
            new ObjectParameter("MAXDATE", typeof(System.DateTime));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_DestecChartCagriDurum_Result>("S_DestecChartCagriDurum", mINDATEParameter, mAXDATEParameter);
    }

    public virtual ObjectResult<S_Destec_CagriIstek_Result> S_Destec_CagriIstek(Nullable<int> iD, Nullable<System.Guid> userId)
    {
        var iDParameter = iD.HasValue ?
            new ObjectParameter("ID", iD) :
            new ObjectParameter("ID", typeof(int));

        var userIdParameter = userId.HasValue ?
            new ObjectParameter("UserId", userId) :
            new ObjectParameter("UserId", typeof(System.Guid));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Destec_CagriIstek_Result>("S_Destec_CagriIstek", iDParameter, userIdParameter);
    }

    public virtual int U_Destec_CagriIstegiKaynakYoneticisiOnayi(Nullable<int> cagriIstegiID, Nullable<bool> islemTipi)
    {
        var cagriIstegiIDParameter = cagriIstegiID.HasValue ?
            new ObjectParameter("CagriIstegiID", cagriIstegiID) :
            new ObjectParameter("CagriIstegiID", typeof(int));

        var islemTipiParameter = islemTipi.HasValue ?
            new ObjectParameter("IslemTipi", islemTipi) :
            new ObjectParameter("IslemTipi", typeof(bool));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("U_Destec_CagriIstegiKaynakYoneticisiOnayi", cagriIstegiIDParameter, islemTipiParameter);
    }

    public virtual int I_Destec_CagriIstegiEvrak(Nullable<int> cagriIstegiID, string evrakAdi)
    {
        var cagriIstegiIDParameter = cagriIstegiID.HasValue ?
            new ObjectParameter("CagriIstegiID", cagriIstegiID) :
            new ObjectParameter("CagriIstegiID", typeof(int));

        var evrakAdiParameter = evrakAdi != null ?
            new ObjectParameter("EvrakAdi", evrakAdi) :
            new ObjectParameter("EvrakAdi", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("I_Destec_CagriIstegiEvrak", cagriIstegiIDParameter, evrakAdiParameter);
    }

    public virtual ObjectResult<S_Destec_CagriIstegiEvrak_Result> S_Destec_CagriIstegiEvrak(Nullable<int> cagriIstekID)
    {
        var cagriIstekIDParameter = cagriIstekID.HasValue ?
            new ObjectParameter("CagriIstekID", cagriIstekID) :
            new ObjectParameter("CagriIstekID", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Destec_CagriIstegiEvrak_Result>("S_Destec_CagriIstegiEvrak", cagriIstekIDParameter);
    }

    public virtual ObjectResult<S_Destec_CagriOnayBekleyen_Result> S_Destec_CagriOnayBekleyen(Nullable<int> iD, Nullable<System.Guid> userId)
    {
        var iDParameter = iD.HasValue ?
            new ObjectParameter("ID", iD) :
            new ObjectParameter("ID", typeof(int));

        var userIdParameter = userId.HasValue ?
            new ObjectParameter("UserId", userId) :
            new ObjectParameter("UserId", typeof(System.Guid));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Destec_CagriOnayBekleyen_Result>("S_Destec_CagriOnayBekleyen", iDParameter, userIdParameter);
    }

    public virtual int U_Destec_CagriTestiniOnayla(Nullable<int> cagriId, Nullable<int> islemTipi, string aciklama)
    {
        var cagriIdParameter = cagriId.HasValue ?
            new ObjectParameter("CagriId", cagriId) :
            new ObjectParameter("CagriId", typeof(int));

        var islemTipiParameter = islemTipi.HasValue ?
            new ObjectParameter("IslemTipi", islemTipi) :
            new ObjectParameter("IslemTipi", typeof(int));

        var aciklamaParameter = aciklama != null ?
            new ObjectParameter("Aciklama", aciklama) :
            new ObjectParameter("Aciklama", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("U_Destec_CagriTestiniOnayla", cagriIdParameter, islemTipiParameter, aciklamaParameter);
    }

    public virtual ObjectResult<S_Destec_CagriKapatilanlar_Result> S_Destec_CagriKapatilanlar(Nullable<int> iD, Nullable<System.Guid> userId)
    {
        var iDParameter = iD.HasValue ?
            new ObjectParameter("ID", iD) :
            new ObjectParameter("ID", typeof(int));

        var userIdParameter = userId.HasValue ?
            new ObjectParameter("UserId", userId) :
            new ObjectParameter("UserId", typeof(System.Guid));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Destec_CagriKapatilanlar_Result>("S_Destec_CagriKapatilanlar", iDParameter, userIdParameter);
    }

    public virtual ObjectResult<S_Destec_CagriOnaylananIstekler_Result> S_Destec_CagriOnaylananIstekler(Nullable<int> iD, Nullable<System.Guid> userId)
    {
        var iDParameter = iD.HasValue ?
            new ObjectParameter("ID", iD) :
            new ObjectParameter("ID", typeof(int));

        var userIdParameter = userId.HasValue ?
            new ObjectParameter("UserId", userId) :
            new ObjectParameter("UserId", typeof(System.Guid));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Destec_CagriOnaylananIstekler_Result>("S_Destec_CagriOnaylananIstekler", iDParameter, userIdParameter);
    }

    public virtual ObjectResult<S_Destec_CagriReddedilenIstekler_Result> S_Destec_CagriReddedilenIstekler(Nullable<int> iD, Nullable<System.Guid> userId)
    {
        var iDParameter = iD.HasValue ?
            new ObjectParameter("ID", iD) :
            new ObjectParameter("ID", typeof(int));

        var userIdParameter = userId.HasValue ?
            new ObjectParameter("UserId", userId) :
            new ObjectParameter("UserId", typeof(System.Guid));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Destec_CagriReddedilenIstekler_Result>("S_Destec_CagriReddedilenIstekler", iDParameter, userIdParameter);
    }

    public virtual ObjectResult<S_Destec_CagriOnaylananIsteklerim_Result> S_Destec_CagriOnaylananIsteklerim(Nullable<int> iD, Nullable<System.Guid> kullaniciId)
    {
        var iDParameter = iD.HasValue ?
            new ObjectParameter("ID", iD) :
            new ObjectParameter("ID", typeof(int));

        var kullaniciIdParameter = kullaniciId.HasValue ?
            new ObjectParameter("KullaniciId", kullaniciId) :
            new ObjectParameter("KullaniciId", typeof(System.Guid));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Destec_CagriOnaylananIsteklerim_Result>("S_Destec_CagriOnaylananIsteklerim", iDParameter, kullaniciIdParameter);
    }

    public virtual ObjectResult<S_Destec_CagriReddedilenIsteklerim_Result> S_Destec_CagriReddedilenIsteklerim(Nullable<int> iD, Nullable<System.Guid> kullaniciId)
    {
        var iDParameter = iD.HasValue ?
            new ObjectParameter("ID", iD) :
            new ObjectParameter("ID", typeof(int));

        var kullaniciIdParameter = kullaniciId.HasValue ?
            new ObjectParameter("KullaniciId", kullaniciId) :
            new ObjectParameter("KullaniciId", typeof(System.Guid));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Destec_CagriReddedilenIsteklerim_Result>("S_Destec_CagriReddedilenIsteklerim", iDParameter, kullaniciIdParameter);
    }

    public virtual ObjectResult<S_Destec_CagriKapatilanlarim_Result> S_Destec_CagriKapatilanlarim(Nullable<int> iD, Nullable<System.Guid> kullaniciId)
    {
        var iDParameter = iD.HasValue ?
            new ObjectParameter("ID", iD) :
            new ObjectParameter("ID", typeof(int));

        var kullaniciIdParameter = kullaniciId.HasValue ?
            new ObjectParameter("KullaniciId", kullaniciId) :
            new ObjectParameter("KullaniciId", typeof(System.Guid));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Destec_CagriKapatilanlarim_Result>("S_Destec_CagriKapatilanlarim", iDParameter, kullaniciIdParameter);
    }

    public virtual ObjectResult<S_Destec_CagriOnayBekleyenlerim_Result> S_Destec_CagriOnayBekleyenlerim(Nullable<int> iD, Nullable<System.Guid> kullaniciId)
    {
        var iDParameter = iD.HasValue ?
            new ObjectParameter("ID", iD) :
            new ObjectParameter("ID", typeof(int));

        var kullaniciIdParameter = kullaniciId.HasValue ?
            new ObjectParameter("KullaniciId", kullaniciId) :
            new ObjectParameter("KullaniciId", typeof(System.Guid));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Destec_CagriOnayBekleyenlerim_Result>("S_Destec_CagriOnayBekleyenlerim", iDParameter, kullaniciIdParameter);
    }

    public virtual ObjectResult<S_Destec_CagriOnayBekleyenIsteklerim_Result> S_Destec_CagriOnayBekleyenIsteklerim(Nullable<int> iD, Nullable<System.Guid> kullaniciId)
    {
        var iDParameter = iD.HasValue ?
            new ObjectParameter("ID", iD) :
            new ObjectParameter("ID", typeof(int));

        var kullaniciIdParameter = kullaniciId.HasValue ?
            new ObjectParameter("KullaniciId", kullaniciId) :
            new ObjectParameter("KullaniciId", typeof(System.Guid));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Destec_CagriOnayBekleyenIsteklerim_Result>("S_Destec_CagriOnayBekleyenIsteklerim", iDParameter, kullaniciIdParameter);
    }

    public virtual ObjectResult<S_Destec_UsersInSirket_GetKullanicininSirketleri_Result> S_Destec_UsersInSirket_GetKullanicininSirketleri(Nullable<System.Guid> userId)
    {
        var userIdParameter = userId.HasValue ?
            new ObjectParameter("UserId", userId) :
            new ObjectParameter("UserId", typeof(System.Guid));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Destec_UsersInSirket_GetKullanicininSirketleri_Result>("S_Destec_UsersInSirket_GetKullanicininSirketleri", userIdParameter);
    }

    public virtual ObjectResult<S_Destec_ModulInSirket_Result> S_Destec_ModulInSirket(Nullable<System.Guid> sirketId)
    {
        var sirketIdParameter = sirketId.HasValue ?
            new ObjectParameter("SirketId", sirketId) :
            new ObjectParameter("SirketId", typeof(System.Guid));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Destec_ModulInSirket_Result>("S_Destec_ModulInSirket", sirketIdParameter);
    }

    public virtual ObjectResult<Nullable<int>> I_Mail(Nullable<int> gonderenDanismanID, string gonderilenMailAdresi, string hTML, Nullable<bool> durum, Nullable<System.DateTime> gonderimTarihi, string gonderenMailAdresi, string konu, string promotionName, Nullable<bool> ekteDosya, string ekteDosyaYolu)
    {
        var gonderenDanismanIDParameter = gonderenDanismanID.HasValue ?
            new ObjectParameter("GonderenDanismanID", gonderenDanismanID) :
            new ObjectParameter("GonderenDanismanID", typeof(int));

        var gonderilenMailAdresiParameter = gonderilenMailAdresi != null ?
            new ObjectParameter("GonderilenMailAdresi", gonderilenMailAdresi) :
            new ObjectParameter("GonderilenMailAdresi", typeof(string));

        var hTMLParameter = hTML != null ?
            new ObjectParameter("HTML", hTML) :
            new ObjectParameter("HTML", typeof(string));

        var durumParameter = durum.HasValue ?
            new ObjectParameter("Durum", durum) :
            new ObjectParameter("Durum", typeof(bool));

        var gonderimTarihiParameter = gonderimTarihi.HasValue ?
            new ObjectParameter("GonderimTarihi", gonderimTarihi) :
            new ObjectParameter("GonderimTarihi", typeof(System.DateTime));

        var gonderenMailAdresiParameter = gonderenMailAdresi != null ?
            new ObjectParameter("GonderenMailAdresi", gonderenMailAdresi) :
            new ObjectParameter("GonderenMailAdresi", typeof(string));

        var konuParameter = konu != null ?
            new ObjectParameter("Konu", konu) :
            new ObjectParameter("Konu", typeof(string));

        var promotionNameParameter = promotionName != null ?
            new ObjectParameter("PromotionName", promotionName) :
            new ObjectParameter("PromotionName", typeof(string));

        var ekteDosyaParameter = ekteDosya.HasValue ?
            new ObjectParameter("EkteDosya", ekteDosya) :
            new ObjectParameter("EkteDosya", typeof(bool));

        var ekteDosyaYoluParameter = ekteDosyaYolu != null ?
            new ObjectParameter("EkteDosyaYolu", ekteDosyaYolu) :
            new ObjectParameter("EkteDosyaYolu", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("I_Mail", gonderenDanismanIDParameter, gonderilenMailAdresiParameter, hTMLParameter, durumParameter, gonderimTarihiParameter, gonderenMailAdresiParameter, konuParameter, promotionNameParameter, ekteDosyaParameter, ekteDosyaYoluParameter);
    }

    public virtual ObjectResult<S_Destec_GonderilecekMailAdresleri_Result> S_Destec_GonderilecekMailAdresleri(Nullable<int> islemTipi, Nullable<System.Guid> userID, Nullable<System.Guid> sirketID, Nullable<int> kayitID)
    {
        var islemTipiParameter = islemTipi.HasValue ?
            new ObjectParameter("IslemTipi", islemTipi) :
            new ObjectParameter("IslemTipi", typeof(int));

        var userIDParameter = userID.HasValue ?
            new ObjectParameter("UserID", userID) :
            new ObjectParameter("UserID", typeof(System.Guid));

        var sirketIDParameter = sirketID.HasValue ?
            new ObjectParameter("SirketID", sirketID) :
            new ObjectParameter("SirketID", typeof(System.Guid));

        var kayitIDParameter = kayitID.HasValue ?
            new ObjectParameter("KayitID", kayitID) :
            new ObjectParameter("KayitID", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Destec_GonderilecekMailAdresleri_Result>("S_Destec_GonderilecekMailAdresleri", islemTipiParameter, userIDParameter, sirketIDParameter, kayitIDParameter);
    }

    public virtual ObjectResult<S_Destec_SirketIDVer_Result> S_Destec_SirketIDVer(string sirketAdi)
    {
        var sirketAdiParameter = sirketAdi != null ?
            new ObjectParameter("SirketAdi", sirketAdi) :
            new ObjectParameter("SirketAdi", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Destec_SirketIDVer_Result>("S_Destec_SirketIDVer", sirketAdiParameter);
    }

    public virtual ObjectResult<S_Destec_CagriIstekIDVer_Result> S_Destec_CagriIstekIDVer(Nullable<int> iD)
    {
        var iDParameter = iD.HasValue ?
            new ObjectParameter("ID", iD) :
            new ObjectParameter("ID", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Destec_CagriIstekIDVer_Result>("S_Destec_CagriIstekIDVer", iDParameter);
    }

    public virtual ObjectResult<S_Destec_Cagri_Result> S_Destec_Cagri(Nullable<int> iD)
    {
        var iDParameter = iD.HasValue ?
            new ObjectParameter("ID", iD) :
            new ObjectParameter("ID", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Destec_Cagri_Result>("S_Destec_Cagri", iDParameter);
    }

    public virtual ObjectResult<S_Destec_AyarlarFirma_Result> S_Destec_AyarlarFirma(Nullable<System.Guid> userID)
    {
        var userIDParameter = userID.HasValue ?
            new ObjectParameter("UserID", userID) :
            new ObjectParameter("UserID", typeof(System.Guid));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Destec_AyarlarFirma_Result>("S_Destec_AyarlarFirma", userIDParameter);
    }
}
