//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class I_Destec_Istek_Result
{
    public Nullable<int> ID { get; set; }
}

public partial class S_Cagri_Result
{
    public int ID { get; set; }
    public int CagriIstekID { get; set; }
    public Nullable<System.DateTime> CagriIstekKayitTarihiSaati { get; set; }
    public string InternalTicketNumber { get; set; }
    public string ExternalTicketNumber { get; set; }
    public string AlternativeTicketNumber { get; set; }
    public string IstekSahibiAdiSoyadi { get; set; }
    public Nullable<System.DateTime> IstekTarihiSaati { get; set; }
    public string IstekSirketAdi { get; set; }
    public string IstekSirketKodu { get; set; }
    public string IstekAciklama { get; set; }
    public System.DateTime SistemKayitTarihiSaati { get; set; }
    public int AtananDanismanID { get; set; }
    public int YonlendirilenDanismanID { get; set; }
    public Nullable<System.DateTime> YonlendirilenDanismanTarihSaati { get; set; }
    public Nullable<System.Guid> KayitOlusturanKullaniciID { get; set; }
    public Nullable<System.Guid> KayitDegistirenKullaniciID { get; set; }
    public int CagriDurumu_TipID1 { get; set; }
}

public partial class S_CagriChart1_Result
{
    public Nullable<System.DateTime> Argument { get; set; }
    public string SeriesName { get; set; }
    public Nullable<int> Value { get; set; }
}

public partial class S_CagriChart2_Result
{
    public string SeriesName { get; set; }
    public Nullable<int> Value { get; set; }
}

public partial class S_Destec_AyarlarFirma_Result
{
    public Nullable<bool> KaynakYoneticisiSistemi { get; set; }
}

public partial class S_Destec_Cagri_Result
{
    public int ID { get; set; }
    public int CagriIstekID { get; set; }
    public Nullable<System.DateTime> CagriIstekKayitTarihiSaati { get; set; }
    public string InternalTicketNumber { get; set; }
    public string ExternalTicketNumber { get; set; }
    public string AlternativeTicketNumber { get; set; }
    public string IstekSahibiAdiSoyadi { get; set; }
    public Nullable<System.DateTime> IstekTarihiSaati { get; set; }
    public string IstekSirketAdi { get; set; }
    public string IstekSirketKodu { get; set; }
    public string IstekAciklama { get; set; }
    public System.DateTime SistemKayitTarihiSaati { get; set; }
    public int AtananDanismanID { get; set; }
    public int YonlendirilenDanismanID { get; set; }
    public Nullable<System.DateTime> YonlendirilenDanismanTarihSaati { get; set; }
    public Nullable<System.Guid> KayitOlusturanKullaniciID { get; set; }
    public Nullable<System.Guid> KayitDegistirenKullaniciID { get; set; }
    public int CagriDurumu_TipID1 { get; set; }
}

public partial class S_Destec_CagriIstegiEvrak_Result
{
    public string EvrakAdi { get; set; }
}

public partial class S_Destec_CagriIstek_Result
{
    public int ID { get; set; }
    public string IstekSahibiAdiSoyadi { get; set; }
    public Nullable<System.DateTime> IstekTarihiSaati { get; set; }
    public string IstekSirketAdi { get; set; }
    public string IstekAciklama { get; set; }
    public int OnemDerecesi { get; set; }
    public string OnemDerecesiAdi { get; set; }
    public string IstekSirketKodu { get; set; }
    public string IstekSahibiMailAdresi { get; set; }
    public string ExternalTicketNumber { get; set; }
    public string AlternativeTicketNumber { get; set; }
    public string Moduller { get; set; }
    public string DosyaEkleri { get; set; }
}

public partial class S_Destec_CagriIstekIDVer_Result
{
    public int ID { get; set; }
    public string IstekSahibiAdiSoyadi { get; set; }
    public Nullable<System.DateTime> IstekTarihiSaati { get; set; }
    public string IstekSirketAdi { get; set; }
    public string IstekAciklama { get; set; }
    public int OnemDerecesi { get; set; }
    public string OnemDerecesiAdi { get; set; }
    public string IstekSirketKodu { get; set; }
    public string IstekSahibiMailAdresi { get; set; }
    public string ExternalTicketNumber { get; set; }
    public string AlternativeTicketNumber { get; set; }
    public string Moduller { get; set; }
    public string DosyaEkleri { get; set; }
}

public partial class S_Destec_CagriKapatilanlar_Result
{
    public int ID { get; set; }
    public string IstekSahibiAdiSoyadi { get; set; }
    public Nullable<System.DateTime> IstekTarihiSaati { get; set; }
    public string IstekSirketAdi { get; set; }
    public string IstekAciklama { get; set; }
    public Nullable<int> OnemDerecesi { get; set; }
    public string OnemDerecesiAdi { get; set; }
    public string IstekSirketKodu { get; set; }
    public string IstekSahibiMailAdresi { get; set; }
    public string ExternalTicketNumber { get; set; }
    public string AlternativeTicketNumber { get; set; }
    public string Moduller { get; set; }
    public string DosyaEkleri { get; set; }
    public string SonucAciklama { get; set; }
    public string InternalTicketNumber { get; set; }
}

public partial class S_Destec_CagriKapatilanlarim_Result
{
    public int ID { get; set; }
    public string IstekSahibiAdiSoyadi { get; set; }
    public Nullable<System.DateTime> IstekTarihiSaati { get; set; }
    public string IstekSirketAdi { get; set; }
    public string IstekAciklama { get; set; }
    public Nullable<int> OnemDerecesi { get; set; }
    public string OnemDerecesiAdi { get; set; }
    public string IstekSirketKodu { get; set; }
    public string IstekSahibiMailAdresi { get; set; }
    public string ExternalTicketNumber { get; set; }
    public string AlternativeTicketNumber { get; set; }
    public string Moduller { get; set; }
    public string DosyaEkleri { get; set; }
    public string SonucAciklama { get; set; }
    public string InternalTicketNumber { get; set; }
}

public partial class S_Destec_CagriOnayBekleyen_Result
{
    public int ID { get; set; }
    public string IstekSahibiAdiSoyadi { get; set; }
    public Nullable<System.DateTime> IstekTarihiSaati { get; set; }
    public string IstekSirketAdi { get; set; }
    public string IstekAciklama { get; set; }
    public Nullable<int> OnemDerecesi { get; set; }
    public string OnemDerecesiAdi { get; set; }
    public string IstekSirketKodu { get; set; }
    public string IstekSahibiMailAdresi { get; set; }
    public string ExternalTicketNumber { get; set; }
    public string AlternativeTicketNumber { get; set; }
    public string Moduller { get; set; }
    public string DosyaEkleri { get; set; }
    public string SonucAciklama { get; set; }
    public string InternalTicketNumber { get; set; }
}

public partial class S_Destec_CagriOnayBekleyenIsteklerim_Result
{
    public int ID { get; set; }
    public string IstekSahibiAdiSoyadi { get; set; }
    public Nullable<System.DateTime> IstekTarihiSaati { get; set; }
    public string IstekSirketAdi { get; set; }
    public string IstekAciklama { get; set; }
    public int OnemDerecesi { get; set; }
    public string OnemDerecesiAdi { get; set; }
    public string IstekSirketKodu { get; set; }
    public string IstekSahibiMailAdresi { get; set; }
    public string ExternalTicketNumber { get; set; }
    public string AlternativeTicketNumber { get; set; }
    public string Moduller { get; set; }
    public string DosyaEkleri { get; set; }
    public string SonucAciklama { get; set; }
}

public partial class S_Destec_CagriOnayBekleyenlerim_Result
{
    public int ID { get; set; }
    public string IstekSahibiAdiSoyadi { get; set; }
    public Nullable<System.DateTime> IstekTarihiSaati { get; set; }
    public string IstekSirketAdi { get; set; }
    public string IstekAciklama { get; set; }
    public Nullable<int> OnemDerecesi { get; set; }
    public string OnemDerecesiAdi { get; set; }
    public string IstekSirketKodu { get; set; }
    public string IstekSahibiMailAdresi { get; set; }
    public string ExternalTicketNumber { get; set; }
    public string AlternativeTicketNumber { get; set; }
    public string Moduller { get; set; }
    public string DosyaEkleri { get; set; }
    public string SonucAciklama { get; set; }
    public string InternalTicketNumber { get; set; }
}

public partial class S_Destec_CagriOnaylananIstekler_Result
{
    public int ID { get; set; }
    public string IstekSahibiAdiSoyadi { get; set; }
    public Nullable<System.DateTime> IstekTarihiSaati { get; set; }
    public string IstekSirketAdi { get; set; }
    public string IstekAciklama { get; set; }
    public int OnemDerecesi { get; set; }
    public string OnemDerecesiAdi { get; set; }
    public string IstekSirketKodu { get; set; }
    public string IstekSahibiMailAdresi { get; set; }
    public string ExternalTicketNumber { get; set; }
    public string AlternativeTicketNumber { get; set; }
    public string Moduller { get; set; }
    public string DosyaEkleri { get; set; }
    public string SonucAciklama { get; set; }
    public int CagriDurumuID { get; set; }
    public string CagriDurumu { get; set; }
    public string InternalTicketNumber { get; set; }
    public string DanismanAdiSoyadi { get; set; }
}

public partial class S_Destec_CagriOnaylananIsteklerim_Result
{
    public int ID { get; set; }
    public string IstekSahibiAdiSoyadi { get; set; }
    public Nullable<System.DateTime> IstekTarihiSaati { get; set; }
    public string IstekSirketAdi { get; set; }
    public string IstekAciklama { get; set; }
    public int OnemDerecesi { get; set; }
    public string OnemDerecesiAdi { get; set; }
    public string IstekSirketKodu { get; set; }
    public string IstekSahibiMailAdresi { get; set; }
    public string ExternalTicketNumber { get; set; }
    public string AlternativeTicketNumber { get; set; }
    public string Moduller { get; set; }
    public string DosyaEkleri { get; set; }
    public string SonucAciklama { get; set; }
    public string DanismanAdiSoyadi { get; set; }
    public string InternalTicketNumber { get; set; }
}

public partial class S_Destec_CagriReddedilenIstekler_Result
{
    public int ID { get; set; }
    public string IstekSahibiAdiSoyadi { get; set; }
    public Nullable<System.DateTime> IstekTarihiSaati { get; set; }
    public string IstekSirketAdi { get; set; }
    public string IstekAciklama { get; set; }
    public int OnemDerecesi { get; set; }
    public string OnemDerecesiAdi { get; set; }
    public string IstekSirketKodu { get; set; }
    public string IstekSahibiMailAdresi { get; set; }
    public string ExternalTicketNumber { get; set; }
    public string AlternativeTicketNumber { get; set; }
    public string Moduller { get; set; }
    public string DosyaEkleri { get; set; }
    public string SonucAciklama { get; set; }
}

public partial class S_Destec_CagriReddedilenIsteklerim_Result
{
    public int ID { get; set; }
    public string IstekSahibiAdiSoyadi { get; set; }
    public Nullable<System.DateTime> IstekTarihiSaati { get; set; }
    public string IstekSirketAdi { get; set; }
    public string IstekAciklama { get; set; }
    public int OnemDerecesi { get; set; }
    public string OnemDerecesiAdi { get; set; }
    public string IstekSirketKodu { get; set; }
    public string IstekSahibiMailAdresi { get; set; }
    public string ExternalTicketNumber { get; set; }
    public string AlternativeTicketNumber { get; set; }
    public string Moduller { get; set; }
    public string DosyaEkleri { get; set; }
    public string SonucAciklama { get; set; }
}

public partial class S_Destec_GonderilecekMailAdresleri_Result
{
    public string MailAdresleri { get; set; }
}

public partial class S_Destec_ModulInSirket_Result
{
    public Nullable<int> ModulID { get; set; }
    public string ModulAdi { get; set; }
}

public partial class S_Destec_SirketIDVer_Result
{
    public System.Guid SirketId { get; set; }
}

public partial class S_Destec_UsersInSirket_GetKullanicininSirketleri_Result
{
    public string SirketAdi { get; set; }
    public Nullable<System.Guid> SirketId { get; set; }
}

public partial class S_DestecChartCagriDurum_Result
{
    public string SeriesName { get; set; }
    public Nullable<int> Value { get; set; }
}

public partial class S_Modul_Result
{
    public int ModulID { get; set; }
    public string ModulAdi { get; set; }
    public Nullable<bool> Sil { get; set; }
}

public partial class S_Tip_Result
{
    public int ID { get; set; }
    public Nullable<int> Ayirac { get; set; }
    public string Aciklama { get; set; }
    public string Notlar { get; set; }
}
